import { useCallback, useEffect, useMemo, useState } from 'react';
import { addEdge, Background, Controls, MiniMap, ReactFlow, useEdgesState, useNodesState, type Connection, type Edge, type Node } from '@xyflow/react';
import '@xyflow/react/dist/style.css';
import { ArrowLeft, Bot, Braces, Check, Clock3, Globe2, GitBranch, Play, Save, Send, Webhook, X } from 'lucide-react';
import { api } from '../services/api';
import type { Workflow } from '../types';

const palette=[['trigger','Webhook',Webhook],['http','HTTP Request',Globe2],['ai','AI Analysis',Bot],['condition','Condition',GitBranch],['transform','Transform',Braces],['delay','Delay',Clock3],['notification','Notification',Send]] as const;
type NodeConfig = Record<string, any>;
type NodeData = {label: string; type: string; config: NodeConfig; retries?: number};
type FlowNode = Node<NodeData>;
const base=(id:string,type:string,label:string,x:number,y:number):FlowNode=>({id,type:'default',position:{x,y},data:{label,type,config:{}}});

export default function WorkflowBuilder({id,onBack}:{id?:string;onBack:()=>void}){
 const [name,setName]=useState('Untitled workflow'); const [nodes,setNodes,onNodesChange]=useNodesState<FlowNode>([]); const [edges,setEdges,onEdgesChange]=useEdgesState<Edge>([]); const [selected,setSelected]=useState<FlowNode|undefined>(); const [saving,setSaving]=useState(false); const [message,setMessage]=useState('');
 useEffect(()=>{if(id) api.get(`/api/workflows/${id}`).then(r=>{setName(r.data.name);setNodes(r.data.nodes||[]);setEdges(r.data.edges||[])})},[id,setEdges,setNodes]);
 const onConnect=useCallback((c:Connection)=>setEdges(es=>addEdge({...c,animated:true},es)),[setEdges]);
 const addNode=(type:string,label:string)=>{const newNode=base(`${type}-${Date.now()}`,type,label,220+(nodes.length%3)*220,140+Math.floor(nodes.length/3)*130);setNodes(ns=>ns.concat(newNode));};
 const save=async():Promise<string|undefined>=>{setSaving(true); const payload={name,description:'Visual automation workflow',enabled:true,nodes,edges}; try{let savedId=id;if(id)await api.put(`/api/workflows/${id}`,payload); else {const r=await api.post('/api/workflows',payload);savedId=r.data.id;history.replaceState({},'',`/workflows/${savedId}`)}setMessage('Saved');setTimeout(()=>setMessage(''),1800);return savedId}finally{setSaving(false)}};
 const run=async()=>{const workflowId=await save();if(workflowId){const r=await api.post(`/api/workflows/${workflowId}/run`,{message:'urgent customer complaint',priority:'high',source:'demo'});setMessage(`Execution ${r.data.id.slice(0,8)} started`);setTimeout(()=>setMessage(''),2200)}};
 const onNodeClick=(_:any,n:FlowNode)=>setSelected(n); const updateConfig=(key:string,value:any)=>{if(!selected)return;const updated={...selected,data:{...selected.data,config:{...selected.data.config,[key]:value}}};setSelected(updated);setNodes(ns=>ns.map(n=>n.id===updated.id?updated:n))};
 return <div className="builder"><div className="builder-top"><button className="icon-btn" onClick={onBack}><ArrowLeft size={17}/></button><input className="name-input" value={name} onChange={e=>setName(e.target.value)}/><div className="builder-spacer"/><span className="save-state">{message}</span><button className="ghost" onClick={save}><Save size={16}/>{saving?'Saving…':'Save'}</button><button className="primary" onClick={run}><Play size={16}/> Run</button></div><div className="builder-body"><aside className="node-palette"><div className="nav-label">NODES</div>{palette.map(([type,label,Icon])=><button key={type} className="palette-item" onClick={()=>addNode(type,label)}><span className="node-icon"><Icon size={15}/></span><span>{label}</span><span className="plus">+</span></button>)}</aside><div className="canvas"><ReactFlow nodes={nodes.map(n=>({...n,selected:n.id===selected?.id}))} edges={edges} onNodesChange={onNodesChange} onEdgesChange={onEdgesChange} onConnect={onConnect} onNodeClick={onNodeClick} fitView colorMode="dark"><Background gap={24} size={1}/><MiniMap/><Controls/></ReactFlow></div><aside className="inspector"><div className="panel-head"><div><div className="nav-label">CONFIGURATION</div><h3>{selected?.data?.label||'Select a node'}</h3></div>{selected&&<button className="icon-btn" onClick={()=>setSelected(undefined)}><X size={15}/></button>}</div>{selected?<Inspector node={selected} update={updateConfig}/>:<div className="inspector-empty"><div className="empty-icon">⌘</div><p>Select a node on the canvas to configure its inputs and behavior.</p></div>}</aside></div></div>
}
function Inspector({node,update}:{node:FlowNode;update:(k:string,v:any)=>void}){const type=node.data.type;const c=node.data.config||{}; const field=(key:string,label:string,value:any,placeholder='')=><label className="field"><span>{label}</span><input value={value??''} placeholder={placeholder} onChange={e=>update(key,e.target.value)}/></label>;return <div className="inspector-body">{type==='http'&&<>{field('method','Method',c.method||'GET')} {field('url','URL',c.url,'https://api.example.com/...')}</>}{type==='ai'&&<>{field('prompt','Prompt',c.prompt||'Classify the incoming data')}<div className="hint">Runs with a local deterministic fallback until an AI provider key is configured.</div></>}{type==='condition'&&<>{field('left','Left value',c.left||'{{priority}}')}<label className="field"><span>Operator</span><select value={c.operator||'equals'} onChange={e=>update('operator',e.target.value)}><option value="equals">equals</option><option value="not_equals">not equals</option><option value="contains">contains</option><option value="greater_than">greater than</option><option value="less_than">less than</option><option value="exists">exists</option></select></label>{field('right','Right value',c.right||'high')}</>}{type==='notification'&&<>{field('provider','Provider',c.provider||'discord')} {field('webhook_url','Webhook URL',c.webhook_url,'https://...')} {field('message','Message',c.message||'FlowForge alert')}</>}{type==='delay'&&field('seconds','Seconds',c.seconds||1)}{type==='transform'&&<>{field('mode','Mode',c.mode||'merge')}{field('data','JSON data',JSON.stringify(c.data||{}))}</>}{type==='trigger'&&<div className="hint">Webhook endpoint: /api/webhooks/{'{workflow_id}'}. Enable the workflow before using it.</div>}<label className="field"><span>Retries</span><input type="number" min="0" max="5" value={node.data.retries??2} onChange={e=>update('retries',Number(e.target.value))}/></label></div>}
