import { useEffect, useState } from 'react';
import { Activity, ArrowRight, CheckCircle2, Clock3, Plus, Sparkles, XCircle } from 'lucide-react';
import { api } from '../services/api';
import type { Workflow } from '../types';
import StatCard from '../components/StatCard';
import WorkflowCard from '../components/WorkflowCard';

export default function Dashboard({openWorkflow}:{openWorkflow:(id?:string)=>void}){
 const [workflows,setWorkflows]=useState<Workflow[]>([]); const [busy,setBusy]=useState(false);
 const load=async()=>{const r=await api.get('/api/workflows');setWorkflows(r.data)}; useEffect(()=>{load()},[]);
 const create=async()=>{const r=await api.post('/api/workflows',{name:'Customer Support Automation',description:'AI triage with alerting and persistence',enabled:true,nodes:[{id:'trigger',type:'default',position:{x:80,y:200},data:{label:'Webhook',type:'trigger',config:{}}},{id:'ai',type:'default',position:{x:350,y:200},data:{label:'AI Analysis',type:'ai',config:{prompt:'Classify incoming request'}}},{id:'condition',type:'default',position:{x:620,y:200},data:{label:'Priority?',type:'condition',config:{left:'{{priority}}',operator:'equals',right:'high'}}},{id:'notify',type:'default',position:{x:900,y:100},data:{label:'Slack Alert',type:'notification',config:{provider:'slack',message:'High priority alert'}}}],edges:[{id:'e1',source:'trigger',target:'ai'},{id:'e2',source:'ai',target:'condition'},{id:'e3',source:'condition',target:'notify'}]});openWorkflow(r.data.id)};
 const run=async(id:string)=>{setBusy(true);try{await api.post(`/api/workflows/${id}/run`,{message:'urgent customer complaint',priority:'high'})}finally{setBusy(false)}};
 return <div className="page"><header className="topbar"><div><div className="eyebrow">OVERVIEW</div><h2>Good evening, Builder.</h2><p>Monitor automation health and ship your next workflow.</p></div><button className="primary" onClick={()=>openWorkflow()}><Plus size={17}/> New workflow</button></header>
 <div className="stats"><StatCard label="Workflows" value={workflows.length} sub="Total automations"/><StatCard label="Executions" value="1,248" sub="+18.6% this month"/><StatCard label="Success rate" value="97.4%" sub="Last 30 days"/><StatCard label="Avg runtime" value="1.82s" sub="-12% vs last month"/></div>
 <div className="grid-2"><section className="panel"><div className="panel-head"><div><h3>Automation health</h3><p>Successful vs failed runs</p></div><Activity size={17}/></div><div className="health-chart"><div className="chart-grid"><span>1.0k</span><span>750</span><span>500</span><span>250</span><span>0</span></div><div className="bars">{[62,78,71,85,77,93,88,96,90,96,92,97].map((h,i)=><div className="bar" style={{height:`${h}%`}} key={i}><i/></div>)}</div></div></section>
 <section className="panel"><div className="panel-head"><div><h3>Execution summary</h3><p>Current platform state</p></div><Sparkles size={17}/></div><div className="summary-list"><div><span><CheckCircle2 size={16}/> Completed</span><strong>1,216</strong></div><div><span><XCircle size={16}/> Failed</span><strong>32</strong></div><div><span><Clock3 size={16}/> Avg wait</span><strong>240ms</strong></div><div><span><Activity size={16}/> Active now</span><strong>6</strong></div></div></section></div>
 <section className="panel"><div className="panel-head"><div><h3>Recent workflows</h3><p>Your latest automation blueprints</p></div><button className="ghost" onClick={create}>{busy?'Creating…':'Use demo workflow'} <ArrowRight size={15}/></button></div><div className="workflow-list">{workflows.length===0?<div className="empty"><GitBranchIcon/><h4>No workflows yet</h4><p>Create your first automation or load the demo.</p><button className="primary" onClick={create}><Plus size={16}/> Create demo</button></div>:workflows.slice(0,5).map(w=><WorkflowCard key={w.id} workflow={w} onOpen={()=>openWorkflow(w.id)} onRun={()=>run(w.id)} onToggle={async()=>{await api.put(`/api/workflows/${w.id}`,{name:w.name,description:w.description,enabled:!w.enabled,nodes:w.nodes,edges:w.edges});load()}}/>)}</div></section>
 </div>}
function GitBranchIcon(){return <div className="empty-icon">◌</div>}
